apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-users-init
  namespace: docucol
data:
  01-init.sh: |
    #!/bin/bash
    set -e
    
    echo "Running Users database initialization..."
    
    # Create extensions if needed
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
      CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
      CREATE EXTENSION IF NOT EXISTS "pg_trgm";
    EOSQL
    
    # Set database parameters for better performance
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
      ALTER SYSTEM SET max_connections = '100';
      ALTER SYSTEM SET shared_buffers = '256MB';
      ALTER SYSTEM SET work_mem = '16MB';
      ALTER SYSTEM SET maintenance_work_mem = '64MB';
      ALTER SYSTEM SET max_wal_size = '1GB';
      ALTER SYSTEM SET effective_cache_size = '512MB';
    EOSQL
    
    echo "Users database initialization completed."
