apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: docucol
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:management-alpine  # Using Alpine-based image for smaller footprint
        ports:
        - name: amqp
          containerPort: 5672
        - name: management
          containerPort: 15672
        env:
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: docucol-secrets
              key: RABBITMQ_USER
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: docucol-secrets
              key: RABBITMQ_PASSWORD
        # Add RabbitMQ specific configuration
        - name: RABBITMQ_ERLANG_COOKIE
          valueFrom:
            secretKeyRef:
              name: docucol-secrets
              key: RABBITMQ_ERLANG_COOKIE
              optional: true
        - name: RABBITMQ_VM_MEMORY_HIGH_WATERMARK
          value: "0.4"  # Lowered memory threshold
        - name: RABBITMQ_DISK_FREE_LIMIT
          value: "2GB"
        - name: RABBITMQ_PLUGINS_EXPAND_DIR
          value: "/var/lib/rabbitmq/plugins-expand"
        # Ultra-lightweight memory optimization
        - name: RABBITMQ_VM_MEMORY_HIGH_WATERMARK_PAGING_RATIO
          value: "0.8"
        - name: RABBITMQ_MNESIA_DUMP_LOG_WRITE_THRESHOLD
          value: "25"
        - name: RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS
          value: "+sbwt none +sbwtdcpu none +sbwtdio none +A4 +MBas ageffcbf +MHas ageffcbf +MBlmbcs 32 +MHlmbcs 32"
        # Disable plugins to reduce memory usage
        - name: RABBITMQ_ENABLED_PLUGINS_FILE
          value: "/etc/rabbitmq/enabled_plugins"
        volumeMounts:
        - name: rabbitmq-data
          mountPath: /var/lib/rabbitmq
        - name: enabled-plugins
          mountPath: /etc/rabbitmq/enabled_plugins
        livenessProbe:
          exec:
            command: ["rabbitmq-diagnostics", "check_port_connectivity"]
          initialDelaySeconds: 60
          periodSeconds: 60
          timeoutSeconds: 15
          failureThreshold: 3
        readinessProbe:
          exec:
            command: ["rabbitmq-diagnostics", "check_running"]
          initialDelaySeconds: 20
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        startupProbe:
          exec:
            command: ["rabbitmq-diagnostics", "check_port_connectivity"]
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 12
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "200m"
            memory: "256Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
        securityContext:
          runAsUser: 999
          runAsGroup: 999
          allowPrivilegeEscalation: false
      volumes:
      - name: rabbitmq-data
        emptyDir: {}
      - name: enabled-plugins
        configMap:
          name: rabbitmq-plugins
          defaultMode: 0644
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: docucol
spec:
  selector:
    app: rabbitmq
  ports:
  - name: amqp
    port: 5672
    targetPort: 5672
  - name: management
    port: 15672
    targetPort: 15672
