apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: docucol
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:management
        ports:
        - name: amqp
          containerPort: 5672
        - name: management
          containerPort: 15672
        env:
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: docucol-secrets
              key: RABBITMQ_USER
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: docucol-secrets
              key: RABBITMQ_PASSWORD
        # Add RabbitMQ specific configuration
        - name: RABBITMQ_ERLANG_COOKIE
          valueFrom:
            secretKeyRef:
              name: docucol-secrets
              key: RABBITMQ_ERLANG_COOKIE
              optional: true
        - name: RABBITMQ_VM_MEMORY_HIGH_WATERMARK
          value: "0.6"
        - name: RABBITMQ_DISK_FREE_LIMIT
          value: "2GB"
        - name: RABBITMQ_PLUGINS_EXPAND_DIR
          value: "/var/lib/rabbitmq/plugins-expand"
        volumeMounts:
        - name: rabbitmq-data
          mountPath: /var/lib/rabbitmq
        livenessProbe:
          exec:
            command: ["rabbitmq-diagnostics", "check_port_connectivity"]
          initialDelaySeconds: 60
          periodSeconds: 60
          timeoutSeconds: 15
          failureThreshold: 3
        readinessProbe:
          exec:
            command: ["rabbitmq-diagnostics", "check_running"]
          initialDelaySeconds: 20
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        startupProbe:
          exec:
            command: ["rabbitmq-diagnostics", "check_port_connectivity"]
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 12
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "1000m"
            memory: "1Gi"
          requests:
            cpu: "200m"
            memory: "512Mi"
        securityContext:
          runAsUser: 999
          runAsGroup: 999
          allowPrivilegeEscalation: false
      volumes:
      - name: rabbitmq-data
        emptyDir: {}  # Use emptyDir instead of PVC for testing/development
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: docucol
spec:
  selector:
    app: rabbitmq
  ports:
  - name: amqp
    port: 5672
    targetPort: 5672
  - name: management
    port: 15672
    targetPort: 15672
